apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: image-pullPolicy-updater
  annotations:
    policies.kyverno.io/version: 1.0.0
    policies.kyverno.io/title: Image Pull Policy Updater
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.6.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      This policy ensures that the imagePullPolicy field is set to IfNotPresent
spec:
  validationFailureAction: enforce
  rules:
    - name: select-pods
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - urlshortener
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (image): "*"
                imagePullPolicy: "IfNotPresent"