name: Generate Templates and Docs

on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Generate Templates and Docs
        run: |
          go run generate-script.go

      - name: Configure Git
        run: |
          git config --global user.email "ashwin@email.com"
          git config --global user.name "Ashwin P"
      
      - name: Print token
        run: echo ${{ secrets.PUSH_SECRET }}

      - name: Commit generated YAML files
        run: |
          git add .
          git commit -m "Generate artifacthub YAML files"
          git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_SECRET }}
          branch: master
