name: Generate Artifact hub files
on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Generate Artifact hub files
        run: |
          go run generate-script.go
          git diff --exit-code || (echo "Please run 'go run generate-script.go to generate artifacts" && exit 1)
